### PR TITLE
bb fixes

### PR DESCRIPTION
**Pull request by Robinlovelace**
Look like we've both worked on this : (

### CODE REVIEW

**Comment by Robinlovelace** [comment]
But I fixed the merge conflict with meld : )

**Comment by mpadge** [comment]
That looks awesome! Thanks so much for the labours. Just one thing: The bit in the vignette about "different overpass API servers" (around previous line#164) is actually really important, and was implemented via #68. Did you mean to delete that?

**Comment by Robinlovelace** [comment]
Yes good point - will do.

**Comment by mpadge** [comment]
@Robinlovelace one more thing while your polishing the vignette: do you think you could address #59? That would be awesome!

**Pull request merged**
