### PR TITLE
Checks in osmdata_* to intercept not implemented query types

### PR DESCRIPTION
**Pull request by jmaspons**
stop cases that crash and warnings for incomplete results.

### CODE REVIEW

**Comment by mpadge** [comment]
Thanks, that's a great addition. I'll just  wait until I've merged #298, then merge that over here before finally merging this one again.

**Comment by jmaspons** [comment]
Ok, I see that you are doing good progress there. Perhaps we can remove many of the errors and warnings from this PR, which is great!

**Comment by jmaspons** [comment]
Testing the `osmdata_*` functions again, I see that the changes for implementing meta queries in C++ for `osmdata_data_frame` doesn't affect the other function. Thus, I think it's OK to merge this PR until addressed

**Review by mpadge — CHANGES_REQUESTED** [review]
Thanks @jmaspons, that looks great. Can you please just make one change, and separate that code which is repeated three times into a separate function? something like `check_not_implemented_query_types(q)`, or a shorter equivalent. `check_query_out_types(q)`? Whatever you think is best. Thanks :+1:

**Comment by jmaspons** [comment]
> separate that code which is repeated three times into a separate function

Done! @mpadge

**Review by mpadge — APPROVED** [review]
Great, thanks so much.

**Pull request merged**
