### PR TITLE
Add parameters from `oqp` to `opq_osm_id`

### PR DESCRIPTION
**Pull request by jmaspons**

### CODE REVIEW

**Review by mpadge — CHANGES_REQUESTED** [review]
Thanks for thinking of that. This is a really cool expansion, but still needs a bit of work to reconciile the kinds of behaviour illustrated in these couple of reprexes.

``` r
devtools::load_all (".", export_all = TRUE)
#> ℹ Loading osmdata
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
id <- 142107768 # Boundary of Bois de Vincennes, Paris: way
x0 <- opq_osm_id (type = "way", id = id) |>
    opq_string () |>
    osmdata_sf ()
n0 <- nrow (x0$osm_points)

dt0 <- "2013-01-01T00:00:00Z"
dt2 <- "2023-03-15T00:00:00Z"

# Expect fewer points in 2013 than 2023:
x1 <- opq_osm_id (type = "way", id = id, datetime = dt0) |>
    opq_string () |>
    osmdata_sf ()
n1 <- nrow (x1$osm_points)
n1 < n0
#> [1] TRUE

# Uninformative error message: should direct people to use
# `osmdata_data_frame()`:
x <- opq_osm_id (type = "way", id = id, datetime = dt0, datetime2 = dt2, adiff = TRUE) |>
    opq_string () |>
    osmdata_sf ()
#> Error in check_not_implemented_queries(obj): adiff queries not yet implemented.

# This is then okay:
x <- opq_osm_id (type = "way", id = id, datetime = dt0, datetime2 = dt2, adiff = TRUE) |>
    opq_string () |>
    osmdata_data_frame ()
nrow (x) < n1
#> [1] TRUE
```

<sup>Created on 2023-03-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Plus then these illustrations of error and warning messages that need to be improved:

``` r
devtools::load_all (".", export_all = TRUE)
#> ℹ Loading osmdata
#> Data (c) OpenStreetMap contributors, ODbL 1.0. https://www.openstreetmap.org/copyright
id <- 7444 # Boundary of Paris, France: relation

# This error message is uninformative, and should direct people to use
# 'osmdata_data_frame()':
x <- opq_osm_id (type = "relation", id = id, out = "tags") |>
    opq_string () |>
    osmdata_sf ()
#> Error in check_not_implemented_queries(obj): Queries returning no geometries 
#> (out tags/ids) not accepted. Use queries with `out="body"` or `out="skel"` instead.

# This then works as expected
x <- opq_osm_id (type = "relation", id = id, out = "tags") |>
    opq_string () |>
    osmdata_data_frame ()

# Same here: the warning (okay in this case), should also direct people to use
# `osmdata_data_frame()`:
x <- opq_osm_id (type = "relation", id = id, out = "meta") |>
    opq_string () |>
    osmdata_sf ()
#> Warning in check_not_implemented_queries(obj): `out meta` queries not yet
#> implemented. Metadata fields will be missing.

# Which again works as expected:
x <- opq_osm_id (type = "relation", id = id, out = "meta") |>
    opq_string () |>
    osmdata_data_frame ()
```

<sup>Created on 2023-03-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jmaspons** [comment]
Hi and thanks for the feedback, @mpadge!

My assumption for the text of the messages is that people using `osmdata_sp/sf/sc` are really interested in the spatial data, thus the message points to changes in the query. Perhaps we can **add** the tip to use `osmdata_xml/data_frame`, as explained in `?opq` details. Is that OK?

**Comment by mpadge** [comment]
> Hi and thanks for the feedback, @mpadge!
> 
> My assumption for the text of the messages is that people using `osmdata_sp/sf/sc` are really interested in the spatial data, thus the message points to changes in the query. Perhaps we can **add** the tip to use `osmdata_xml/data_frame`, as explained in `?opq` details. Is that OK?

Yeah, sorry, I should have explained better, but that was exactly what I meant. Just adding some extra information to current errors/warnings.

**Comment by jmaspons** [comment]
I improved the messages, @mpadge. Ready to merge now?

**Review by mpadge — APPROVED** [review]
Great, that's much better, thanks

**Pull request merged**
